version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    restart: unless-stopped
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data

volumes:
  dynamodb_data:
