seller:
  username: str
  telegram_user_id: int
  business_name: str
  contact_email: str
  contact_phone: int
  homepage: str
  display_name: str
  active: bool
  registered: bool
  created_at: date

known_buyer: []

promo:
  promo_id: str
  start_date: date
  end_date: date
  display_name: str
  image_url: str
  description: str
  price: float
  shipping_costs: float
  display_message: str
  channel_id: str
  product_limit: int
  options: dict[str, str]
  timer: {}
